name: je_kit
description: A Flutter package for foundation and common widget.
version: 0.0.1
homepage: https://github.com/jayden320/je_kit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.1.0
  url_launcher: ^6.1.2
  oktoast: ^3.2.0
  device_info: ^2.0.3
  permission_handler: ^9.2.0
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  intl: ^0.17.0
  image_gallery_saver: ^1.7.1
  package_info_plus: ^3.1.2
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.10
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
